// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace restoran.Migrations
{
    [DbContext(typeof(RestoranContext))]
    [Migration("20220106220149_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Models.Dezert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("ImeDezerta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Dezert");
                });

            modelBuilder.Entity("Models.Jela", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("ImeJela")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Jela");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrojTelefona")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Klijent");
                });

            modelBuilder.Entity("Models.Narudzbina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DezertID")
                        .HasColumnType("int");

                    b.Property<int?>("JelaID")
                        .HasColumnType("int");

                    b.Property<int?>("KlijentID")
                        .HasColumnType("int");

                    b.Property<int?>("PicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DezertID");

                    b.HasIndex("JelaID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("PicaID");

                    b.ToTable("Narudzbina");
                });

            modelBuilder.Entity("Models.Pica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("ImePica")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Piće");
                });

            modelBuilder.Entity("Models.Narudzbina", b =>
                {
                    b.HasOne("Models.Dezert", "Dezert")
                        .WithMany("DezertiNaruci")
                        .HasForeignKey("DezertID");

                    b.HasOne("Models.Jela", "Jela")
                        .WithMany("JelaNaruci")
                        .HasForeignKey("JelaID");

                    b.HasOne("Models.Klijent", "Klijent")
                        .WithMany("Klijenti")
                        .HasForeignKey("KlijentID");

                    b.HasOne("Models.Pica", "Pica")
                        .WithMany("PicaNaruci")
                        .HasForeignKey("PicaID");

                    b.Navigation("Dezert");

                    b.Navigation("Jela");

                    b.Navigation("Klijent");

                    b.Navigation("Pica");
                });

            modelBuilder.Entity("Models.Dezert", b =>
                {
                    b.Navigation("DezertiNaruci");
                });

            modelBuilder.Entity("Models.Jela", b =>
                {
                    b.Navigation("JelaNaruci");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.Navigation("Klijenti");
                });

            modelBuilder.Entity("Models.Pica", b =>
                {
                    b.Navigation("PicaNaruci");
                });
#pragma warning restore 612, 618
        }
    }
}
